version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: estudiodigital
      POSTGRES_USER: adminestudiodigital
      POSTGRES_PASSWORD: passwordestudiodigital
